services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-service:
    build: ./auth-service
    image: auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - db-auth
      - kafka
      - user-management-service

  user-management-service:
    build: ./user-management-service
    image: user-management-service
    container_name: user-management-service
    ports:
      - "8081:8081"
    depends_on:
      - db-user
      - kafka
      - moderation-service

  moderation-service:
    build: ./moderation-service
    image: moderation-service
    container_name: moderation-service
    ports:
      - "8082:8082"
    depends_on:
      - db-moder
      - kafka
      - music-content-service

  music-content-service:
    build: ./music-content-service
    image: music-content-service
    container_name: music-content-service
    ports:
      - "8083:8083"
    depends_on:
      - db-music
      - kafka
      - playlist-service

  playlist-service:
    build: ./playlist-service
    image: playlist-service
    container_name: playlist-service
    ports:
      - "8084:8084"
    depends_on:
      - db-playlist
      - kafka
      - search-service

  search-service:
    build: ./search-service
    image: search-service
    container_name: search-service
    ports:
      - "8085:8085"
    depends_on:
      - db-search
      - kafka
      - streaming-service

  streaming-service:
    build: ./streaming-service
    image: streaming-service
    container_name: streaming-service
    ports:
      - "8086:8086"
    depends_on:
      - db-stream
      - kafka
      - album-service

  album-service:
    build: ./album-service
    image: album-service
    container_name: album-service
    ports:
      - "8087:8087"
    depends_on:
      - db-album
      - kafka
      - auth-service

  db-album:
    image: postgres
    container_name: db-album
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=album
      - POSTGRES_USER=album
      - POSTGRES_PASSWORD=album

  db-auth:
    image: postgres
    container_name: db-auth
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth

  db-moder:
    image: postgres
    container_name: db-moder
    ports:
      - "6543:5434"
    environment:
      - POSTGRES_DB=moder
      - POSTGRES_USER=moder
      - POSTGRES_PASSWORD=moder

  db-music:
    image: postgres
    container_name: db-music
    ports:
      - "6544:5435"
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music

  db-playlist:
    image: postgres
    container_name: db-playlist
    ports:
      - "6545:5436"
    environment:
      - POSTGRES_DB=playlist
      - POSTGRES_USER=playlist
      - POSTGRES_PASSWORD=playlist

  db-search:
    image: postgres
    container_name: db-search
    ports:
      - "6546:5437"
    environment:
      - POSTGRES_DB=search
      - POSTGRES_USER=search
      - POSTGRES_PASSWORD=search

  db-stream:
    image: postgres
    container_name: db-stream
    ports:
      - "6547:5438"
    environment:
      - POSTGRES_DB=stream
      - POSTGRES_USER=stream
      - POSTGRES_PASSWORD=stream

  db-user:
    image: postgres
    container_name: db-user
    ports:
      - "6548:5439"
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

